'use client'; // Error components must be Client components

import { useEffect } from 'react';
import { Metadata } from 'next';
import Link from 'next/link';

import { PageBody, PageTitle } from "@/app/components/PageMain";
import { MarketPaths } from '@/database/constants';

export const metadata: Metadata = {
    title: "Error",
    // description: "Generated by create next app",
};

export default function Error({
    error,
    // reset,
}: {
    error: Error;
    // reset: () => void;
}) {
    useEffect(() => {
        // Log the error to an error reporting service
        console.error(error);
    }, [error]);

    return (<div className="page">
        <PageTitle title_text="404 Error" />
        <PageBody>
            <section id="section-1" className="section">
                <div className="section-body">
                    <Link
                        href={MarketPaths.HOME}
                        className="btn-secondary"
                    >
                        Back to Home
                    </Link>
                </div>
            </section>
        </PageBody>
    </div>);
}